requirements-dev.txt
setup.cfg

add qiskit-qasm3-import dev dependency

Ryanhill1 patch 1

---

qbraid/transpiler/tests/coverage/test_coverage_from_braket.py
qbraid/transpiler/tests/coverage/test_coverage_from_cirq.py
qbraid/transpiler/tests/coverage/test_coverage_from_pyquil.py
qbraid/transpiler/tests/coverage/test_coverage_from_pytket.py
qbraid/transpiler/tests/coverage/test_coverage_from_qiskit.py

ALLOWANCE of +2 for benchmark testing

add allowance to baseline threshold

---

docs/sdk/devices.rst
qbraid/transpiler/tests/benchmarking/qiskit_to_braket.py
requirements-dev.txt

Add script that compares accuracy of qiskit --> braket conversions for qBraid vs qiskit-braket-provider

Rh1 benchmark

---

qbraid/transpiler/tests/coverage/coverage.md
qbraid/transpiler/tests/coverage/test_coverage_from_braket.py
qbraid/transpiler/tests/coverage/test_coverage_from_cirq.py
qbraid/transpiler/tests/coverage/test_coverage_from_pyquil.py
qbraid/transpiler/tests/coverage/test_coverage_from_pytket.py
qbraid/transpiler/tests/coverage/test_coverage_from_qiskit.py

set random seed for coverage tests to ensure reproducibility
add markdown doc tracking coverage accuracy

coverage rand seeds + doc

---

qbraid/interface/qbraid_qasm/circuit_drawer.py
qbraid/interface/qbraid_qasm/tests/test_circuit_drawer.py

Resolves https://github.com/qBraid/qBraid/issues/269
Fixed issue with SWAP gates being drawn incorrectly
Additional issue with string formatting resolved
Added additional test to confirm functionality
Add an `x` between the boxes braket that apply, meaning to complete the check before any merge happen, feel free to ask help if you are unsure about anything.

Fixed qubit indexing issue with SWAP gate

---

.github/workflows/docs.yml
.github/workflows/format.yml
.github/workflows/main.yml
.github/workflows/test-publish.yml
.github/workflows/unit-tests.yml
README.md

update image and try to fix build issue

Rh1 deps updates

---

docs/lab/gpu.rst
requirements.txt
setup.cfg

update braket version

---

qbraid/_version.py
qbraid/api/session.py
qbraid/api/tests/test_api_config.py
requirements.txt
setup.cfg

Rh1 qbraid jobs bug

---

qbraid/interface/qbraid_qasm/bell.qasm
qbraid/interface/qbraid_qasm/shared_15.qasm
qbraid/interface/qbraid_qasm/tests/test_qasm_utils.py
qbraid/interface/qbraid_qasm/tools.py
qbraid/transpiler/__init__.py
qbraid/transpiler/wrappers/qasm3_str.py
requirements-dev.txt
requirements.txt
setup.cfg

- qasm num qubits works for qasm 2 & 3
- qasm 2 depth no cirq dependency
- qasm 3 depth function (TODO: rm qiskit dependency)
- qasm 3 circuit wrapper class (TODO: link to transpiler circuit conversion fn)

QASM updates - utils + wrapper 

---

qbraid/interface/qbraid_braket/tools.py
qbraid/interface/tests/test_convert_to_contiguous.py
qbraid/transpiler/cirq_braket/__init__.py
qbraid/transpiler/cirq_braket/convert_braket_qasm.py
qbraid/transpiler/cirq_braket/convert_to_braket.py
qbraid/transpiler/cirq_braket/tests/test_braket_qasm.py
qbraid/transpiler/tests/benchmarking/qiskit_to_braket.py

account for braket control modifiers and add braket from qasm3 conversion fn

braket updates

---

ecosystem.json
qbraid/api/__init__.py
qbraid/api/job_api.py
qbraid/providers/job.py
requirements-dev.txt
requirements.txt

test generate new coverage report

move job api + deps updates

---

docs/sdk/jobs.rst
qbraid/providers/aws/__init__.py
qbraid/providers/aws/job.py
qbraid/providers/aws/tracker.py
qbraid/providers/job.py
tests/providers/conftest.py
tests/providers/fixtures.py
tests/providers/test_braket_tracker.py

function that gets USD cost of AWS quantum task. Retroactively extends native Amazon Braket cost tracker

aws task cost

---

qbraid/get_jobs.py
qbraid/load_provider.py
qbraid/providers/job.py
requirements-dev.txt
setup.cfg
tests/fixtures/braket/gates.py

Bug fix with GPhase: https://github.com/amazon-braket/amazon-braket-sdk-python/commit/d5af538079d9cbb6f065da46e1e6731145e2a71b

bump braket

---

README.md
qbraid/_version.py
qbraid/api/session.py
qbraid/get_devices.py

- fix import error in get_devices for no ipython dependency
- update conversion graph so renders on pypi

import error optional dependency bug fix

---

qbraid/get_devices.py
qbraid/get_jobs.py

- abstract fetch data from get jobs function similar to in get devices so helper can be used by CLI

get jobs update - abstract fetch data

---

tox.ini

*issue tag(s), if applicable*:

fix workflow set config

---

README.md
pyproject.toml
qbraid/providers/device.py
qbraid/providers/ibm/device.py
requirements-dev.txt

*issue tag(s), if applicable*:

fix typos and bump braket

---

CITATION.cff
CONTRIBUTING.md
README.md
docs/api/qbraid.transforms.rst
docs/index.rst
pyproject.toml
qbraid/__init__.py
qbraid/_version.py
qbraid/providers/aws/device.py
qbraid/providers/device.py
qbraid/providers/ibm/device.py
qbraid/providers/ibm/provider.py
qbraid/transforms/__init__.py
qbraid/transforms/exceptions.py
qbraid/transforms/pytket/__init__.py
qbraid/transforms/pytket/ionq.py
tests/transforms/test_pytket_transforms.py
tox.ini

- renamed "qbraid.compiler" to "qbraid.transforms"
- simplified device runtime flow by combining abstract transpile & compile methods into one transform method

transforms module (compiler stand-in)

---

.github/workflows/main.yml
pyproject.toml
requirements-dev.txt

deps updates

---

pyproject.toml
requirements.txt
tests/providers/test_braket_tracker.py
tools/set_provider_configs.py

update qbraid-core + aws configure

---

pyproject.toml
qbraid/transpiler/conversions/__init__.py
requirements-dev.txt

conversion nodes fix

---

README.md
SECURITY.md

post bump updates

---

docs/api/qbraid.runtime.rst
pyproject.toml
qbraid/runtime/__init__.py
qbraid/runtime/braket/device.py
qbraid/runtime/braket/job.py
qbraid/runtime/device.py
qbraid/runtime/ionq/__init__.py
qbraid/runtime/ionq/device.py
qbraid/runtime/ionq/job.py
qbraid/runtime/ionq/provider.py
qbraid/runtime/ionq/result.py
qbraid/transforms/qasm2/passes.py
requirements-dev.txt
tests/fixtures/__init__.py
tests/runtime/test_braket_provider.py

ionq provider classes

---

pyproject.toml
qbraid/runtime/native/provider.py
tests/runtime/test_quantum_device.py
tests/top_level/test_display.py
tools/set_provider_configs.py
tox.ini

- add mock tests for remainder of tests requiring qbraid api key

Qbraid mock tests

---

docs/api/qbraid.runtime.rst
docs/conf.py
pyproject.toml
qbraid/__init__.py
qbraid/runtime/__init__.py
qbraid/runtime/native/job.py
qbraid/runtime/native/result.py
qbraid/runtime/oqc/__init__.py
qbraid/runtime/oqc/device.py
qbraid/runtime/oqc/job.py
qbraid/runtime/oqc/provider.py
qbraid/runtime/oqc/result.py
requirements-dev.txt
tests/runtime/test_oqc_provider.py

qir simulator + oqc compat

---

pyproject.toml
tests/runtime/test_ionq_provider.py

Resolve #624 
- I am contributing to this project as a unitaryHACK participant

Implement tests for IonQ runtime provider

---

qbraid/runtime/oqc/device.py
qbraid/runtime/oqc/job.py
qbraid/runtime/oqc/provider.py
qbraid/runtime/oqc/result.py
qbraid/runtime/qiskit/job.py
qbraid/runtime/qiskit/result.py
qbraid/runtime/result.py
tests/runtime/test_oqc_provider.py
tests/runtime/test_qiskit_provider.py
tests/runtime/test_quantum_results.py
tests/transforms/test_qasm_format.py

qiskit result + oqc shuffle

---

qbraid/runtime/oqc/job.py
tests/runtime/test_oqc_provider.py

make oqc metadata more readable

---

qbraid/runtime/native/provider.py
tests/runtime/test_quantum_device.py
tests/top_level/test_display.py

runtime provider + device class test cases

---

qbraid/programs/libs/qasm2.py
qbraid/runtime/braket/availability.py
qbraid/runtime/braket/provider.py
qbraid/runtime/native/result.py
tests/programs/test_program_libs_cirq.py
tests/programs/test_program_libs_qasm2.py
tests/programs/test_program_libs_qasm3.py
tests/programs/test_program_type_alias_manager.py
tests/programs/test_program_type_registry.py
tests/runtime/test_braket_runtime.py
tests/runtime/test_quantum_results.py

testing updates

---

tests/runtime/test_braket_ahs_ir.py

serialize ahs

---

qbraid/transpiler/conversions/cirq/cirq_to_braket.py
tests/transpiler/braket/test_cirq_to_braket.py

cirq->braket for ionq gates support

---

qbraid/transpiler/conversions/__init__.py
qbraid/transpiler/conversions/braket/braket_extras.py
qbraid/transpiler/conversions/braket_ahs/__init__.py
qbraid/transpiler/conversions/braket_ahs/braket_ahs_extras.py
tests/transpiler/bloqade/test_bloqade_to_braket_ahs.py

move braket_ahs / bloqade conversion

---

qbraid/passes/qasm3/compat.py
qbraid/transpiler/conversions/cirq/cirq_quil_output.py
qbraid/transpiler/conversions/cirq/cirq_to_qasm2.py
tests/passes/test_qasm3_compat.py
tests/programs/test_program_circuits_pyquil.py
tests/programs/test_program_circuits_qiskit.py
tests/runtime/test_target_profile.py
tests/transpiler/braket/test_braket_to_cirq.py
tests/transpiler/cirq/test_cirq_to_braket.py
tests/transpiler/pyquil/test_quil_output.py

more codecov!

---

.github/PULL_REQUEST_TEMPLATE.md
CITATION.cff
README.md
pyproject.toml

pre-release housekeep

---

qbraid/runtime/braket/availability.py
tests/programs/test_program_circuits_qasm3.py
tests/runtime/test_braket_availability.py
tests/runtime/test_braket_runtime.py
tests/runtime/test_ionq_runtime.py
tests/runtime/test_oqc_runtime.py
tests/runtime/test_quantum_device.py
tests/runtime/test_quantum_job.py
tests/runtime/test_quantum_results.py

more codecoverage

---

pyproject.toml
requirements-dev.txt

Deps update

---

qbraid/runtime/oqc/device.py
qbraid/runtime/oqc/provider.py
tests/runtime/test_ionq_runtime.py
tests/runtime/test_oqc_runtime.py

Changes made according to requests made by the OQC team.
Waiting for response from OQC team on the `get_next_window` usage before merging.

OQC Runtime Fix

---

.github/workflows/ci-daily.yml
pyproject.toml
qbraid/transpiler/conversions/qiskit/qiskit_extras.py
qbraid/transpiler/edge.py
requirements-dev.txt
tests/transpiler/qasm/test_conversions_qasm3.py
tests/transpiler/test_conversion_extras.py
tests/transpiler/test_conversion_graph.py
tox.ini

update qiskit dep + debug statement in tox

---

CHANGELOG.md
qbraid/_version.py

bump patch version

---

CHANGELOG.md
pyproject.toml
qbraid/_version.py
qbraid/runtime/native/result.py
requirements-dev.txt

- bump amazon braket version to allow for new rigetti ankaa-2 device

bump version

---

CHANGELOG.md
qbraid/_version.py
qbraid/runtime/native/provider.py
tests/runtime/test_quantum_device.py

- removed fixed provider value from QbraidProvider target profile, allow to be populated from API data

enable adding new device from API

---

CHANGELOG.md
CONTRIBUTING.md
qbraid/interface/random/qiskit_random.py
qbraid/programs/__init__.py
qbraid/programs/alias_manager.py
qbraid/programs/program.py
qbraid/programs/qasm_typer.py
qbraid/programs/registry.py
qbraid/runtime/enums.py
qbraid/runtime/native/device.py
qbraid/runtime/native/provider.py
qbraid/transpiler/conversions/qasm2/qasm2_to_qasm3.py
qbraid/transpiler/edge.py
qbraid/transpiler/graph.py
qbraid/transpiler/scheme.py
tests/programs/test_interface.py
tests/programs/test_program_qasm_typer.py
tests/programs/test_program_type_alias_manager.py
tests/runtime/test_quantum_device.py
tests/runtime/test_target_profile.py
tests/transpiler/test_conversion_edge.py
tests/transpiler/test_conversion_graph.py

- expanding native runtime `QbraidProvider` + `QbraidDevice` to accommodate new devices beyond the QIR simulator
- bug fixes related to the transpiler and how shortest conversion paths were calculated
- enhanced typing for openqasm for both static type checking and isinstance checks

expand runtime native + transpiler bug fixes

---

CHANGELOG.md
qbraid/runtime/device.py
qbraid/runtime/native/device.py
requirements.txt
tests/runtime/test_quantum_device.py

Fixes #742 by adding `estimate_cost` method for devices using `qbraid_core`

Add `estimate_cost` method to `qbraid.runtime.device.QuantumDevice`

---

pyproject.toml
qbraid/runtime/braket.py
qbraid/runtime/qiskit.py
qbraid/runtime/result.py
requirements.txt
tests/runtime/test_quantum_device.py

- add deprecation warnings for `result.measurements()` and `result.measurement_counts()`

deprecation warnings

---

CHANGELOG.md
README.md
qbraid/_version.py

update changelog, readme, version

---

qbraid/runtime/ionq/provider.py

- The `IONQ_API_KEY` env var should be present in the API's .env file. The value will be a "valid" api key, representing qBraid's IONQ credits.

`IonQProvider` update for `IonQ` devices integration

---

pyproject.toml
qbraid/runtime/native/device.py
qbraid/runtime/native/job.py
requirements.txt

- cache terminal status values
- memory option for qir runner
- bump qbraid-core version

cache status + memory value

---

.github/workflows/docs.yml
.github/workflows/format.yml
.github/workflows/main.yml
.github/workflows/pr-compliance.yml
CHANGELOG.md
pyproject.toml
qbraid/_version.py
requirements-dev.txt
tests/visualization/test_circuit_drawer.py

- Update workflows with changelog reminder and conditional runs for draft PRs

PR compliance

---

pyproject.toml
qbraid/programs/__init__.py
qbraid/programs/_import.py
qbraid/programs/annealing/__init__.py
qbraid/programs/annealing/_model.py
qbraid/programs/annealing/cpp_pyqubo.py
qbraid/runtime/native/device.py
qbraid/runtime/native/provider.py
qbraid/runtime/schemas/experiment.py
requirements-dev.txt
tests/programs/test_program_annealing.py
tests/runtime/_resources.py
tests/runtime/test_device.py

- add annealing tests
- pyqubo runtime updates

annealing programs + pyqubo runtime updates

---

CHANGELOG.md
qbraid/runtime/schemas/device.py

make noise models optional

---

CHANGELOG.md
qbraid/_version.py
qbraid/runtime/schemas/experiment.py
tests/runtime/test_schemas.py

- Add pydantic schema to define the possible Qubo solve params available for submissions to the NEC vector annealer device

Qubo solve params schema

---

.github/ISSUE_TEMPLATE/bug_report.yml
CHANGELOG.md

- Improved clarity of bug report prompts

Improve clarity of bug report prompts

---

.github/workflows/pr-compliance.yml
CHANGELOG.md
docs/index.rst
qbraid/runtime/native/device.py
qbraid/runtime/native/provider.py
qbraid/runtime/schemas/__init__.py
tests/runtime/_resources.py
tests/runtime/test_device.py

- Handle bug failure to raise error if native device dependency extra not installed

handle target spec package not installed

---

qbraid/passes/qasm/compat.py
tests/passes/test_qasm3_compat.py

- more handling of edge cases for convert qasm pi to decimal

qasm pi to decimal edge cases

---

CHANGELOG.md
qbraid/_version.py
qbraid/runtime/native/provider.py
tests/runtime/test_device.py

- validation for ionq qasm programs before submitting via native qbraid provider

add native ionq validation step

---

CHANGELOG.md
CITATION.cff
CONTRIBUTING.md
qbraid/runtime/ionq/provider.py
qbraid/runtime/native/device.py
qbraid/runtime/native/provider.py
qbraid/runtime/schemas/job.py
tests/runtime/test_device.py

- some additional logic for submitting to ionq devices from native provider including error mitigation field
- updated examples submodule & add note to contributing doc

native provider ionq device patch

---

CHANGELOG.md
pyproject.toml
qbraid/transpiler/conversions/qasm3/qasm3_to_ionq.py
tests/transpiler/qasm/test_qasm_to_ionq.py

- Update pyqasm optional dependency
- Update examples repo link

Update examples + pyqasm dep

---

CHANGELOG.md
qbraid/_version.py
qbraid/interface/random/cirq_random.py
qbraid/interface/random/qiskit_random.py
qbraid/passes/qasm/__init__.py
qbraid/passes/qasm/compat.py
qbraid/runtime/oqc/device.py
tests/passes/test_qasm3_compat.py
tests/programs/test_interface.py
tests/runtime/oqc/test_oqc_runtime.py

- remove "include" statements from qasm strings submitted to OQC devices
- update next available window logic for Toshiko QPU
- remove defaults from OQC compiler config

OQC qasm format + device availability fixes

---

CHANGELOG.md
qbraid/runtime/native/job.py
qbraid/runtime/schemas/experiment.py
qbraid/runtime/schemas/job.py
tests/runtime/test_device.py
tests/runtime/test_schemas.py

- Updated validators for `AhsExperimentMetadata` pydantic model/schema
- Added `QbraidJob.queue_position()` method

AHS expt schema & native job queue position

---

CHANGELOG.md
qbraid/programs/loader.py
qbraid/visualization/plot_conversions.py

- Updated doc string  & improved type hinting of `qbraid.load_program`
- Display seed in bottom left corner of conversion graph if `plot_conversion_graph` called with `legend=True`

load pg typing + plot conv seed shown

---

CHANGELOG.md
CITATION.cff
qbraid/_version.py
tests/runtime/native/test_nec_vector_annealer_runtime.py
tests/transpiler/cirq/test_qasm_parser.py

- Post release updates (bump dev version + update citation)
- Fix `nec_vector_annealer` remote test. Generalized solutions check

Post release + remote test fix

---

CHANGELOG.md
CITATION.cff
README.md

- pyqasm post merge updates including citation, change log, readme, and examples link

Pyqasm post merge

---

CHANGELOG.md
CITATION.cff
README.md
qbraid/runtime/ibm/device.py
qbraid/runtime/ibm/job.py
qbraid/runtime/ibm/result_builder.py

- fix num args passed to `SamplerV2.run`
- raise `NotImplementedError` for `QiskitJob.queue position()` if not available
- Account for `DataBin` pub result data type `c` attribute instead of `meas`

fix qiskit runtime sampler job submission

---

CHANGELOG.md
CITATION.cff
tests/programs/test_program_annealing.py

- update examples sub-module
- bump citation date and version
- reset changelog

Prepare release

---

CHANGELOG.md
README.md
docs/conf.py
qbraid/_caching.py
qbraid/passes/__init__.py
qbraid/programs/_import.py
qbraid/programs/ahs/__init__.py
qbraid/programs/annealing/__init__.py
qbraid/programs/gate_model/__init__.py
qbraid/runtime/oqc/job.py
qbraid/runtime/postprocess.py
qbraid/transpiler/conversions/__init__.py
qbraid/transpiler/conversions/qasm2/__init__.py
tests/runtime/_resources.py

- Update conversion graph and QPROGRAM registry on README.md

Update README.md and register `qibo` dynamic

---

CHANGELOG.md
qbraid/transpiler/graph.py
qbraid/transpiler/scheme.py
qbraid/visualization/plot_conversions.py
tests/visualization/test_plot_conversions.py

- Fixed `plt.show` / `plt.save_fig` bug in `plot conversion_graph`
- Improved `plot_runtime_conversion_scheme` by removing edges not within `ConversionScheme.max_path_depth`

Conversion graph plotting fixes

---

CHANGELOG.md
qbraid/transpiler/conversions/qasm3/qasm3_to_ionq.py
requirements-dev.txt
tests/transpiler/qasm/test_qasm_to_ionq.py

- Update `qasm3_to_ionq` conversion: no longer need to check if pyqasm is installed (required dep)

fix ionq conversion test

---

CHANGELOG.md
pyproject.toml
qbraid/programs/typer.py
qbraid/runtime/__init__.py
qbraid/runtime/device.py
qbraid/runtime/loader.py
qbraid/runtime/native/provider.py
requirements-dev.txt
requirements.txt
tests/programs/test_program_type_alias_manager.py
tests/runtime/test_loader.py
tests/top_level/test_about.py
tests/transpiler/test_transpiler.py

- Added logger `DEBUG` statements to `QuantumDevice` that track with the steps in job submission runtime
- Expanded list of natively supported hardware vendors to include Rigetti, OQC, and IQM

logger debug stmts, new devices, load_provider

---

qbraid/_version.py

Bump dev version [no ci]

---

.github/workflows/ci-daily.yml
.github/workflows/main.yml
CHANGELOG.md
requirements-cudaq.txt
requirements-dev.txt
tox.ini

- reset cudaq integration tests - move back to one tox env

cudaq integration tests coverage rest

---

CHANGELOG.md
qbraid/runtime/ibm/provider.py
qbraid/runtime/postprocess.py
requirements-dev.txt
tests/runtime/ibm/test_qiskit_runtime.py
tests/runtime/test_result.py

- Loosen relative tolerance for `distribute_counts` function
- Update `QiskitRuntimeProvider` with annotations for cloud credentials

Probs sum to 1 relative tol + IBM credentials

---

CHANGELOG.md
requirements.txt

- Pin `pyqasm` version to 0.3.0 mitigate bug: https://github.com/qBraid/pyqasm/issues/175

Pin pyqasm version

---

CHANGELOG.md
requirements.txt

Bump pyqasm version to `>=0.3.2, < 0.4.0`

Bump pyqasm version to `>=0.3.2, < 0.4.0`

---

CHANGELOG.md
qbraid/_version.py

- update dev version to 0.9.6.dev
- fix typo in changelog and rm duplicate entry

update dev version [no ci]

---

CHANGELOG.md

- Reset changelog in preparation for release 0.9.7

Reset CHANGELOG.md for new version [no ci]

---

CHANGELOG.md
docs/conf.py
qbraid/passes/qasm/compat.py
qbraid/programs/_import.py
qbraid/transpiler/conversions/braket/braket_to_qasm3.py
qbraid/transpiler/conversions/qasm3/__init__.py
qbraid/transpiler/conversions/qasm3/qasm3_extras.py
requirements-dev.txt
tests/fixtures/autoqasm/circuits.py
tests/passes/test_qasm3_compat.py
tests/transpiler/test_conversion_extras.py

- Addressed #1013 - AutoQASM to QASM3 (str) conversion extra
- Implemented tests for `autoqasm_to_qasm3` method

autoqasm-qasm3 conversion extra

---

CHANGELOG.md
README.md
pyproject.toml
requirements-dev.txt

- Updated `examples` submodule
- Updated `amazon-braket-sdk` depedency for IQM Emerald
- Added `autoqasm` to` QPROGRAM_REGISTRY` in `README.md`
- Reset `CHANGELOG.md` for release 0.9.8

prep release

---

CHANGELOG.md

Fix CHANGELOG PR link [no ci]

---

CHANGELOG.md
tests/runtime/azure/test_azure_remote.py

- Skip remote Azure provider tests that now require payed plan

skip remote azure tests that now require payed plan

---

CONTRIBUTING.md
README.md
tests/runtime/test_job.py

Fix minor typos
- Yor -> Your
- neccessary -> necessary
- experiements -> experiments
- automaically -> automatically
- recieved -> received

Fix minor typos

---

CHANGELOG.md
qbraid/programs/gate_model/qasm2.py
qbraid/programs/gate_model/qasm3.py
requirements.txt

- Support latest version of pyqasm 0.5.0

Bump pyqasm requirement
