qBraid/qBraid

qbraid/interface/tests/test_programs.py, requirements.txt, setup.cfg
Requirements bumps allowing latest pytket thanks to loosening of networkx requirements in pyquil and cirq:
https://github.com/rigetti/pyquil/pull/1584
https://github.com/quantumlib/Cirq/pull/6105
=> bump requirements

README.md, docs/sdk/circuits.rst, docs/sdk/overview.rst, qbraid/_qprogram.py, qbraid/interface/__init__.py, qbraid/interface/calculate_unitary.py, qbraid/interface/convert_to_contiguous.py, qbraid/interface/qbraid_qiskit/tools.py, qbraid/transpiler/cirq_qiskit/conversions.py, qbraid/transpiler/conversions.py, qbraid/transpiler/tests/test_transpiler.py
add qasm3 support integrations into all cross-framework functions
e.g. convert to contiguous, calculate unitary, conversions, etc.
=> integrate qasm3

CITATION.cff, qbraid/compiler/braket/ionq.py, qbraid/compiler/exceptions.py, qbraid/transpiler/cirq_pyquil/quil_output.py, qbraid/transpiler/conversions.py, tests/_data/programs.py, tests/benchmarking/qiskit_to_braket.py, tests/compiler/test_braket_compiler.py, tests/interface/test_calculate_unitary.py, tests/interface/test_cirq_tools.py, tests/interface/test_convert_to_contiguous.py, tests/interface/test_programs.py, tests/interface/test_qasm3_utils.py, tests/interface/test_qiskit_tools.py, tests/transpiler/cirq_pyquil/test_quil_output.py, tests/transpiler/code/test_qasm_to_braket.py, tests/transpiler/coverage/test_coverage_from_braket.py, tests/transpiler/coverage/test_coverage_from_cirq.py, tests/transpiler/coverage/test_coverage_from_pyquil.py, tests/transpiler/coverage/test_coverage_from_pytket.py, tests/transpiler/coverage/test_coverage_from_qiskit.py, tests/transpiler/test_conversions.py, tests/transpiler/test_transpiler.py, tools/verify_headers.py, tox.ini
- Addressed all errors/warnings raised from applying `pylint` checks over `tests` module
- Converted some qasm3 tests to use `pytest.mark.parametrize`
- Replaced assertion in braket ionq compiler function to raise new `CompilerError`
=> improve formatting of unit tests + housekeeping

qbraid/interface/qbraid_qasm3/tools.py, tests/interface/test_qasm3_utils.py
Issue : #298 
PR : [398](https://github.com/qBraid/qBraid/pull/398) [contd.]
Add new implementation for the `_convert_to_contiguous_qasm3` function 
- Adds a compression function `_compress_to_contiguous_qasm3` alongside the `_expand_to_contiguous_qasm3` to create a contiguous qasm3 string
- Refactored the `_convert_to_contiguous_qasm3` to use the new implementations
- Logic for compression was as discussed in the older PR, have added unit test to validate it
Add an `x` between the boxes braket that apply, meaning to complete the check before any merge happen, feel free to ask help if you are unsure about anything.
=> Add implementation for `contiguous` compression [contd]

qbraid/transpiler/braket/conversions_qasm.py, tests/transpiler/cirq_braket/test_braket_qasm3.py
qiskit and braket define various standard gates in slightly different ways in OpenQASM 3, see below. These mismatches were previously accounted for for braket $\rightarrow$ qiskit conversions, but not for qiskit $\rightarrow$ braket conversions. This PR now considers these gate def maps both directions.
**OpenQASM 3 standard gate definitions**
| Qiskit           | Amazon Braket  |
| ------------| ---------------- |
| cx | cnot | 
| sdg | si | 
| tdg | ti | 
| sx | v | 
| sxdg | vi | 
| p | phaseshift | 
| cp | cphaseshift |
=> braket qasm3 mapped gates fix

qbraid/programs/cirq.py, tests/programs/test_cirq_program.py
cirq NamedQubits without any index were failing to be parsed to int e.g. NamedQubit("q") was failing. So fixed for convert to line qubits with extra conditional and added patch in for the get int from qubit function which is naive but should work for most cases.
=> patch cirq named qubit bug

README.md, pyproject.toml, qbraid/_about.py, qbraid/_compat.py, qbraid/transforms/pytket/ionq.py, qbraid/transpiler/converter.py, qbraid/transpiler/graph.py, qbraid/visualization/plot_conversions.py, requirements.txt, tests/top_level/test_about.py, tests/transpiler/test_conversion_grah.py, tests/transpiler/test_converter.py, tools/set_provider_configs.py, tox.ini
- Resolve #618
- `networkx` is removed from requirements
- I added `rustworkx` to a pylint whitelist to disable `no-member` error
- I added `DecomposeBoxes` pass in `harmony_transform()` because `RebaseCustom` pass cannot handle gates like `ECR`, `GPi`, etc. when converting braket circuit to pytket circuit at `test_pytket_ionq.py`. (The reason the error did not occur before seems to be that `rustworkx` returns the top shortest conversion paths in a different order than `networkx`. For the record, if `networkx` is used than the conversion path is `['braket', 'cirq', 'qasm2', 'pytket']`, but if we use `rustworkx` it becomes `['braket', 'qiskit', 'qasm2', 'pytket']`)
(I am contributing to this project as a unitaryHACK participant)
Please review the checklist below and mark items with an `x` …
=> Use `rx.PyDiGraph` for `ConversionGraph`

qbraid/runtime/ionq/device.py, tests/runtime/test_ionq_device.py
- Resolve #625 
- `IonQDevice.extract_gate_data()` now supports the following gates in openqasm3 program:
- `x`, `not`
- `y`
- `z`
- `rx`
- `ry`
- `rz`
- `h`
- `cnot`, `cx`, `CX`, `ccx`, `toffoli`
- `s`
- `sdg`, `si`
- `t`
- `tdg`, `ti`
- `sx`, `v`
- `sxdg`, `vi`
- `swap`
</body>
</html>
- I am contributing to this project as a unitaryHACK participant
=> Expand IonQ provider runtime to supported gates

qbraid/transpiler/edge.py, tests/transpiler/test_conversion_edge.py
made a small mistake; 
current deployment uses weights $w = \dfrac{1}{a}$ where $a \in [0, 1.0]$ is the accuracy of the conversion. this is incorrect:
consider two paths from $A \to C$: $A \to B_1 \to C$ and $A\to B_2 \to C$. let the first path have accuracies of $\dfrac 14$ and $\dfrac 16$ whereas the two conversions in the second half both have accuracy $\dfrac 15$.  that is, the weights are 4, 6 and 5, 5 respectively.  the current implementation will consider these paths the same weight, as they both sum to 10. however, $\dfrac{1}{24} > \dfrac{1}{25}$, so we would want to prefer the first path over the second.
the fix just takes the logarithms of the current weight. this works because:
1. djikstra's is an algorithm that finds the minimum ***sum*** of edge weights
2. $\log$ is an …
=> conversion graph weighting fix

CHANGELOG.md, qbraid/runtime/ionq/provider.py, qbraid/runtime/oqc/device.py, qbraid/runtime/oqc/provider.py, tests/runtime/test_oqc_runtime.py
- In data returned from OQC client, 'feature_set' was assumed to be json format, but in reality was encoded as string. This caused caused errors both with provider get_devices and device status methods which are both now fixed.
=> fix oqc provider json decoding error

qbraid/runtime/ionq/job.py, tests/runtime/ionq/test_ionq_runtime.py
- Updated the `metadata` function for ionq job metadata to be used on the `api` side
=> Add metadata for `IonQJob` in runtime 

CHANGELOG.md, qbraid/programs/circuits/qasm.py, qbraid/transpiler/conversions/qasm2/qasm2_to_ionq.py, tests/programs/test_program_circuits_qasm2.py, tests/transpiler/qasm/test_qasm2_to_ionq.py
Fixes #769 
- Update the `qasm2_to_ionq` conversion to include full registers being applied as quantum gate arguments 
- Moreover, the number of qubits used in gate application is not reflective of the number of qubits on which a gate acts on. Eg. `h q[0], q[1];` means `h` is being applied on 2 qubits but is itself a 1-qubit gate. Updated the logic to identify this based on gate name instead of actual qubit arguments.
- Some other updates for representing the bits of qasm programs for easier handling
=> Improve support for gates in `qasm2_to_ionq` conversion

CHANGELOG.md, qbraid/passes/qasm/compat.py, tests/passes/test_qasm3_compat.py
- Fixed bug in `qbraid.passes.qasm.convert_qasm_pi_to_decimal()` where `gpi` and `gpi2` gate defs were being subbed with pi decimal value. Fix is not perfect but will work for most cases.
=> fix gpi qasm gate pi decimal bug

CHANGELOG.md, pyproject.toml, qbraid/programs/_import.py, qbraid/programs/ahs/_model.py, qbraid/programs/ahs/braket_ahs.py, qbraid/programs/annealing/__init__.py, qbraid/programs/annealing/_model.py, qbraid/programs/annealing/cpp_pyqubo.py, qbraid/programs/annealing/qubo.py, qbraid/programs/typer.py, qbraid/runtime/device.py, qbraid/runtime/native/device.py, qbraid/runtime/native/provider.py, tests/programs/test_program_abc.py, tests/programs/test_program_ahs_braket.py, tests/programs/test_program_annealing.py, tests/programs/test_program_meta_typer.py, tests/runtime/native/test_nec_vector_annealer_runtime.py, tests/runtime/test_device.py
- Register Qubo coefficients program type
- Remove offset from annealing problem types (now just in QuboSolveParams)
- Update runtime logic for nec vector annealer to support "qubo" program spec type
=> Annealing program types updates for nec vector annealer jobs

CHANGELOG.md, CITATION.cff, qbraid/_version.py, qbraid/runtime/__init__.py, qbraid/runtime/aws/job.py, qbraid/runtime/aws/result_builder.py, qbraid/runtime/azure/job.py, qbraid/runtime/ibm/job.py, qbraid/runtime/ionq/job.py, qbraid/runtime/job.py, qbraid/runtime/native/device.py, qbraid/runtime/native/job.py, qbraid/runtime/native/result.py, qbraid/runtime/oqc/job.py, qbraid/runtime/result.py, qbraid/runtime/result_data.py, tests/runtime/test_device.py, tests/runtime/test_result.py
- Enhanced type hinting for the `Result.data` property by leveraging a custom `typing.TypeVar`, enabling automatic adaptation to the specific `ResultData` subclass being accessed.
- Added support for specifying different `quera_qasm_simulator` backends in the `QbraidDevice.run` method using the "backend" keyword argument (e.g., "cirq", "cirq-gpu")
=> result data type hints

CHANGELOG.md, qbraid/passes/qasm/__init__.py, qbraid/passes/qasm/compat.py, qbraid/transpiler/conversions/openqasm3/openqasm3_to_ionq.py, qbraid/transpiler/conversions/qasm3/qasm3_to_braket.py, qbraid/transpiler/conversions/qasm3/qasm3_to_qiskit.py, tests/passes/test_qasm3_compat.py
- Renamed the function `replace_gate_name` to `replace_gate_names` and updated its implementation to accept a dictionary of gate name mappings instead of individual old and new gate names. (`qbraid/passes/qasm/compat.py`)
- Added `p` to `z` gate name mapping to `openqasm3_to_ionq` conversion
=> replace gate names

CHANGELOG.md, qbraid/passes/qasm/decompose.py, qbraid/programs/gate_model/ionq.py, qbraid/runtime/ionq/job.py, qbraid/runtime/postprocess.py, qbraid/transpiler/conversions/openqasm3/openqasm3_to_ionq.py, tests/runtime/ionq/test_ionq_runtime.py, tests/runtime/test_device.py, tests/runtime/test_result.py, tests/transpiler/qasm/test_qasm_to_ionq.py
- `qbraid/programs/gate_model/ionq.py`: Added support for new gates including `cx`, `cy`, `cz`, `crx`, `cry`, `crz`, `ch`, `ccnot`, `cs`, `csi`, `ct`, `cti`, `cv`, `cvi`.
- `qbraid/passes/qasm/decompose.py`: Updated the `rebase` function to handle gate mappings with predicates.
- `qbraid/transpiler/conversions/openqasm3/openqasm3_to_ionq.py`: Refactored gate mappings and added validation for gate parameters and qubit counts.
- `qbraid/runtime/postprocess.py`: Added `distribute_counts` function to adjust probabilistic counts ensuring the total equals the number of shots.
- `qbraid/runtime/ionq/job.py`: Integrated `distribute_counts` function in `convert_to_counts` method.
=> add support for ionq controlled gates

.github/workflows/ci-daily.yml, .github/workflows/pre-release.yml, .github/workflows/publish.yml, CHANGELOG.md, MANIFEST.in, pyproject.toml, qbraid/_about.py, qbraid/transpiler/conversions/cirq/cirq_quil_output.py, qbraid/transpiler/conversions/cirq/cirq_to_pyquil.py, qbraid/transpiler/conversions/openqasm3/openqasm3_to_ionq.py, qbraid/transpiler/conversions/qasm2/cirq_custom.py, qbraid/transpiler/conversions/qasm2/cirq_qasm_parser.py, qbraid/transpiler/conversions/qasm2/qasm2_to_cirq.py, requirements-dev.txt, tests/fixtures/qiskit/gates.py, tests/runtime/oqc/test_oqc_runtime.py, tests/transpiler/pyquil/test_conversions_pyquil.py, tests/transpiler/pyquil/test_quil_output.py, tests/transpiler/qasm/test_cirq_custom.py, tests/transpiler/qiskit/test_conversions_qiskit.py, tests/transpiler/qiskit/test_coverage_from_qiskit.py, tox.ini
- Removed Python 3.9 from daily test matrix and restricted PyPI publish jobs to specific actors for better security and maintainability.
- Updated `MANIFEST.in` to refine file inclusion/exclusion and enhanced `pyproject.toml` by adjusting dependencies and aligning with `requirements.txt`.
- Enhanced qbraid transpiler functions with better type annotations, external gate handling, and radians-based updates for the `RZZGate`.
- Added testing code coverage for custom `rzz`, `u3`, and `u2` for Cirq $\rightarrow$ PyQuil
=> housekeep, rzz, code coverage

CHANGELOG.md, pyproject.toml, qbraid/programs/gate_model/ionq.py, qbraid/programs/gate_model/qasm2.py, qbraid/programs/gate_model/qasm3.py, qbraid/runtime/ionq/device.py, qbraid/transpiler/annotations.py, qbraid/transpiler/conversions/braket/braket_to_cirq.py, qbraid/transpiler/conversions/openqasm3/openqasm3_to_ionq.py, qbraid/transpiler/conversions/qiskit/qiskit_to_qasm2.py, qbraid/visualization/exceptions.py, qbraid/visualization/plot_conversions.py, requirements-dev.txt, tests/fixtures/pytket/circuits.py, tests/runtime/ionq/test_ionq_runtime.py, tests/runtime/test_device.py, tests/transpiler/qasm/test_qasm_to_ionq.py, tests/transpiler/test_conversion_edge.py, tox.ini
- Add `id` gate to list of supported IonQ gates, but skip in transformation
- Add retry in IonQDevice transform method using pyqasm unrolling
- Remove qasm barriers before submitting to qBraid QIR device
- fix some type checking in transpiler weight and requires extras annotations
- IonQ runtime updates related to:
- #877 
- #840
=> IonQ runtime fixes

CHANGELOG.md, pyproject.toml, qbraid/programs/ahs/_model.py, qbraid/programs/annealing/_model.py, qbraid/programs/gate_model/_model.py, qbraid/programs/gate_model/braket.py, qbraid/programs/gate_model/ionq.py, qbraid/programs/gate_model/qasm2.py, qbraid/programs/gate_model/qasm3.py, qbraid/programs/program.py, qbraid/programs/spec.py, qbraid/programs/typer.py, qbraid/runtime/__init__.py, qbraid/runtime/azure/job.py, qbraid/runtime/azure/provider.py, qbraid/runtime/device.py, qbraid/runtime/ibm/job.py, qbraid/runtime/ionq/job.py, qbraid/runtime/ionq/provider.py, qbraid/runtime/loader.py, qbraid/runtime/native/device.py, qbraid/runtime/native/provider.py, qbraid/runtime/oqc/job.py, tests/programs/test_program_annealing.py, tests/programs/test_program_circuits_ionq.py, tests/programs/test_program_type_registry_qir.py, tests/runtime/ibm/test_qiskit_runtime.py, tests/runtime/native/test_aws_simulators_runtime.py, tests/runtime/native/test_quera_aquila_runtime.py, tests/runtime/test_load_job.py
- Added `qbraid.runtime.load_job` function that uses entrypoints to load provider job class and create instance with job id
- Switched all `QbraidJob` sub-classes to only require `job_id` as positional argument, and any other args that used to be required for auth can now be loaded with credentials from environment variables 
- Added `QuantumProgram.serialize` method to streamline creation of `ProgramSpec` classes in `QbraidProvider`
=> program serialization and load_job

CHANGELOG.md, qbraid/runtime/postprocess.py, tests/runtime/test_result.py
Fixes an issue with IonQ backends, whose result probabilities not always sum to exactly 1.
Data from a real IonQ scenario:
```
'probabilities': ... {'0': 0.097980373, '1': 0.251172315, '2': 0.639023034, '3': 0.011824277} ...
```
where the sum is 0.999999999 and not exactly 1.
Unit tested with `tox -e unit-tests -- tests/runtime/test_result.py`
=> Allow min tolerance in postprocessing check of result probabilities sum

CHANGELOG.md, tests/runtime/ionq/test_ionq_runtime.py
- Add `qpu.forte-enterprise` devices to `IonQProvider` runtime tests
=> Add `qpu.forte-enterprise` devices IonQ rt tests

CHANGELOG.md, pyproject.toml, qbraid/__init__.py, qbraid/runtime/postprocess.py, qbraid/transpiler/__init__.py, qbraid/transpiler/conversions/__init__.py, qbraid/transpiler/conversions/qiskit/qiskit_extras.py, qbraid/transpiler/converter.py, requirements-dev.txt, requirements.txt, tests/runtime/native/test_nec_vector_annealer_runtime.py, tests/runtime/test_result.py, tests/transpiler/test_translate.py
- Handle counts dict empty in format counts fn
- Add `translate` functions as alias for `transpile`, but also that can chain multiple conversions together 
For example:
```python
from qbraid import translate
circuit_out = translate(circuit_in, "qasm3", "braket", "cirq")
```
=> Runtime fixes + translate alias

.github/workflows/bump-version.yml, .github/workflows/gh-pages.yml, .github/workflows/pr-compliance.yml, CHANGELOG.md, CITATION.cff, docs/_static/css/custom.css, docs/index.rst, pyproject.toml, qbraid/programs/gate_model/ionq.py, qbraid/runtime/aws/job.py, qbraid/runtime/ionq/device.py, qbraid/runtime/ionq/provider.py, qbraid/transpiler/conversions/openqasm3/openqasm3_to_ionq.py, requirements-dev.txt, tests/runtime/azure/test_azure_runtime.py, tests/runtime/native/test_ionq_runtime_remote.py, tests/runtime/native/test_quera_aquila_runtime.py, tests/transpiler/qasm/test_qasm_to_ionq.py, tests/transpiler/test_transpiler.py
- Added a workflow for deploying to GitHub Pages on release publication or manual dispatch.
- Updated `bump-version.yml` to track `qbraid/_version.py` instead of `pyproject.toml`.
- Adjusted docs side navigation search styling for better alignment.
- Added support for interpreting `zz` as a QIS gate in `openqasm3_to_ionq` and refactored `determine_gateset` accordingly
- Modified `openqasm3_to_ionq` to emit warning instead of raise error when circuits contains measurements.
- Fixed bug where `BraketQuantumTask._task.arn` undefined if instaniated without `AwsQuantumTask` object
=> IonQ zz bug + housekeep

CHANGELOG.md, qbraid/runtime/ibm/provider.py, tests/runtime/ibm/test_qiskit_runtime.py
Consider the following snippet instantiating an IBM Quantum provider backend.
```python3
provider = QiskitRuntimeProvider()
device = provider.get_device("ibm_sherbrooke")
print(device.profile.basis_gates)
```
Output before PR:
```
None
```
Output after PR:
```
{'x', 'ecr', 'id', 'rz', 'sx'}
```
=> Populate basis gates in IBM Quantum provider backends

.github/workflows/pr-compliance.yml, CHANGELOG.md, tests/runtime/oqc/test_oqc_runtime.py
- Temporarily skip remote OQC tests because the QCaaS servers will be offline until March 17, 2025.
=> Skip OQC remote tests - QCaaS servers offline

CHANGELOG.md, tests/runtime/azure/test_azure_remote.py
- Added pytest.skip statements to Azure remote tests to skip them when the relevant device is not online.
=> skip azure remote test(s) if device is offline

CHANGELOG.md, qbraid/runtime/job.py, requirements-dev.txt, tests/runtime/test_job.py
This PR introduces asynchronous support for job completion:
- `QuantumJob._wait_for_final_state()` - an `async` version of `wait_for_final_state()` using `asyncio.sleep`.
- `QbraidJob.async_result()` - an async wrapper that waits for job completion and returns the result.
- Associated tests using `pytest.mark.asyncio` for both success and timeout scenarios.
- All functions include proper docstrings and type hints.
The async variant allows non-blocking job monitoring in event-loop-driven applications such as async pipelines and UIs.
Closes #942
=> Add async support for waiting on QuantumJob completion

CHANGELOG.md, qbraid/runtime/job.py, qbraid/runtime/schemas/base.py, requirements.txt
- Removed the `strict=False` parameter from the `pydantic_core.core_schema.union_schema()` calls in the `__get_pydantic_core_schema__` method(s) in `qbraid.runtime.schemas.base`. `stric` parameter no longer included in the `pydantic-core` API for that method as of release [v0.2.30](https://github.com/pydantic/pydantic-core/releases/tag/v2.30.0), PR [#1638](https://github.com/pydantic/pydantic-core/pull/1638).
- Added `pydantic-core` to project requirements
=> Remove `strict` param from `pydantic_core` union schema calls

CHANGELOG.md, tests/runtime/aws/test_braket_remote.py
- Changed catch `JobStateError` to `TimeoutError` in braket remote test
=> Fixed braket remote test timeout error

CHANGELOG.md, qbraid/runtime/device.py, tests/runtime/test_device.py
- Added `QbraidDevice.set_target_program_type`, allowing you to set a specific `ProgramSpec` (from `TargetProfile`) alias as the default. For example, if a device supports both "qasm2" and "qasm3", you can now restrict transpilation to one format:
```python
from qbraid.runtime import IonQProvider
provider = IonQProvider()
device = provider.get_device("simulator")
device.metadata()["runtime_config"]["target_program_type"] # ['qasm2', 'qasm3']
device.set_target_program_type("qasm2")
device.metadata()["runtime_config"]["target_program_type"] # 'qasm2'
```
However the original `TargetProfile.program_spec` value remains frozen:
```python
device.profile.program_spec
```
=> Add set target program type method to QbraidDevice

CHANGELOG.md, qbraid/runtime/azure/provider.py, qbraid/runtime/azure/result_builder.py, tests/runtime/azure/test_azure_runtime.py
Non-simulator target profiles on Azure follow the pattern `provider_id.qpu.device_id`, see https://learn.microsoft.com/en-us/azure/quantum/qc-target-list
Old code was not working as it'd compare the string `qpu.device_id` against `qpu`, producing ill results. 
```python3
from qbraid.runtime import AzureQuantumProvider
provider = AzureQuantumProvider()
device = provider.get_device("ionq.simulator")
assert(device.simulator)
device = provider.get_device("ionq.qpu.aria-1")
assert(not device.simulator)
```
`tox -e unit-tests -- tests/runtime/azure/test_azure_runtime.py`
=> Fix simulator check for Azure targets

CHANGELOG.md, docs/conf.py, qbraid/programs/_import.py, qbraid/transpiler/conversions/qasm2/__init__.py, qbraid/transpiler/conversions/qasm2/qasm2_extras.py, qbraid/transpiler/converter.py, requirements-dev.txt, tests/transpiler/qasm/test_conversions_pyqpanda3.py
This PR adds support for transpiling between [`pyqpanda3`](https://qcloud.originqc.com.cn/document/qpanda-3/index.html) and QASM2.
The testing checking pyqpanda3 -> qasm2 is failing however, as pyqpanda3 is adding a `creg c[0];` to the QASM output, even though there are no classical bits involved in the circuit. The qasm2 parser that is testing for equivalence between two qasm 2 strings is raising an error that the `creg` size must be positive. 
Closes #961 
(TODO: Update changelog)
=> Add support for transpiling QASM2 to/from pyqpanda3

CHANGELOG.md, qbraid/runtime/aws/provider.py, tests/runtime/aws/test_braket_runtime.py
Reference PR : [#1098 | api ](https://github.com/qBraid/api/pull/1098)
* Added support for `aws_session_token` in the `BraketProvider` class (`qbraid/runtime/aws/provider.py`)
* Updated the `_get_aws_session` method to include the `aws_session_token` parameter when creating an AWS session. (`qbraid/runtime/aws/provider.py`)
* Modified the `__hash__` method of `BraketProvider` to include `aws_session_token` in the hash computation, ensuring unique identification for instances with different session tokens. (`qbraid/runtime/aws/provider.py`)
=> BYOT AWS `BraketProvider` changes

CHANGELOG.md, qbraid/_version.py, qbraid/programs/gate_model/cudaq.py, qbraid/runtime/native/provider.py, qbraid/visualization/plot_counts.py, tests/fixtures/qir/bell.ll, tests/programs/test_program_cudaq.py
- Add `CudaQKernel.serialize` method that converts cudaq program to QIR string for `run_input` compatible format for `QbraidDevice.submit`.
- Fixed lazy importing bug in `plot_histogram` method
=> cudaq qir serialization + plt counts import fix

CHANGELOG.md, qbraid/transpiler/conversions/braket/braket_to_cirq.py
- Fix bug which caused all braket conversions to be unavailable if cirq was not installed due to top-level cirq import in `braket_to_cirq.py` which should have been done lazily.
=> fix braket cirq lazy import bug

CHANGELOG.md, qbraid/runtime/native/job.py, qbraid/runtime/schemas/job.py, tests/runtime/azure/test_azure_runtime.py, tests/runtime/test_schemas.py
- Removed `queue_position` from result details, as it is always `None` and not applicable.
- Updated `TimeStamps` schema to auto-compute `executionDuration` from `createdAt` and `endedAt` if not explicitly provided.
- Enhanced `TimeStamps` to accept both `datetime.datetime` objects for `createdAt` and `endedAt` (previously only accepted ISO-formatted strings).
- Made Pulser unit test version-agnostic to support any installed Pulser version.
=> Queue position, timestamps, pulser versioning

CHANGELOG.md, qbraid/transpiler/graph.py, tests/transpiler/test_conversion_graph.py
Okay, so I could figure out that the main error comes from loading the default conversions in this line,
https://github.com/qBraid/qBraid/blob/d3f6614b5ea3c58fe0fe1a0a79be68638673e26c/qbraid/transpiler/graph.py#L132-L147
This PR makes changes to only consider `source` and `target` in `conversion_functions` that are present/registered in `QPROGRAM_ALIASES`, hence solving the bug mentioned in #789. 
Closes #789.
=> Circumvent constructing unregistered program type nodes in `ConversionGraph`

CHANGELOG.md, qbraid/runtime/azure/result_builder.py, qbraid/runtime/ionq/job.py, qbraid/runtime/postprocess.py, qbraid/runtime/result_data.py, tests/runtime/azure/test_azure_runtime.py, tests/runtime/test_result.py
This PR adds a `measurement_probabilities` argument to the `GateModelResultData` class.
TODO:
Closes #785
=> Add measurement_probabilties argument to GateModelResultData class

CHANGELOG.md, qbraid/visualization/plot_conversions.py
The autoscaling that matplotlib uses will sometimes cause the plot to be clipped. This is more likely to occur when using the "scatter" plot function with large symbols. This change does two things:
1) Explicitly creates a matplotlib figure object and associated Axes instance and passes the Axes instance to mpl_draw
2) After mpl_draw returns, a margin of 15% is added to the plot.
The margin around the plot allows the contents to be rendered without clipping.
Note that currently, the margin is hard coded at 15%. To make this more flexible it could be added as an extra keyword argument for the plot_conversion_graph function.
Potentially closes #851
=> Add margins for conv graph plot 

CHANGELOG.md, qbraid/_entrypoints.py, qbraid/_version.py, qbraid/programs/loader.py, requirements.txt, tests/top_level/test_import.py
- Removed legacy `pkg_resources` logic for loading entry points, as support for Python 3.9 has been dropped and the project now requires Python 3.10 or higher.
=> Remove `pkg_resources` from entrypoints logic

CHANGELOG.md, qbraid/runtime/postprocess.py, tests/runtime/test_result.py
As discussed on the thread of [this issue](https://github.com/unitaryfoundation/metriq-gym/issues/386), we decided to demote the probability sum not being equal to 1 from a `ValueError` to a `UserWarning`.
=> fix: alter raise of warning instead of value error for probability sum.

CHANGELOG.md, qbraid/runtime/native/result.py, qbraid/runtime/schemas/experiment.py, qbraid/runtime/schemas/job.py, tests/runtime/native/test_equal1_runtime.py
- This pull request refactors how base64 decoding is handled for the `compiled_output` field in Equal1 simulation results and metadata. The decoding logic is moved from the `Equal1SimulatorResultData` class to the `Equal1SimulationMetadata` schema, ensuring that compiled outputs are automatically decoded when metadata is instantiated. Associated tests have been updated and expanded to verify this behavior and to improve coverage for result/metadata interactions.
- For `equal1_simulator` jobs, the `base64` decoded compiled output will now be accessible from a `Result` object as follows:
```python
result = job.result()
compiled_output = result.details['metadata']['compiledOutput']
```
=> Equal1: decode compiled output in result details

CHANGELOG.md, pyproject.toml, qbraid/transpiler/conversions/cirq/cirq_quil_output.py, qbraid/transpiler/conversions/qasm2/cirq_qasm_parser.py, requirements-dev.txt, tests/transpiler/cirq/test_conversions_cirq.py
Fixes #977 
This PR updates the QASM Parser and related code for Cirq to PyQuil transpilation. 
The [Cirq v1.5 Parser](https://github.com/quantumlib/Cirq/blob/7fe741bfbce2a58f803ecb04d577bb45802fb2f4/cirq-core/cirq/contrib/qasm_import/_parser.py#L515) separated `pi` from `terms`, requiring a small addition to the `cirq_qasm_parser.py`.
This resolved all QASM Parser issues, except for the decomposition of some gates (like Controlled-Y) which now include a `cirq.global_phase_operation()`. Since the QASM Parser does not recognize this operation, the code around the decomposition was modified to **NOT** send the global phase to the QASM Parser. 
Tests were added for `cirq.global_phase_operation()` to ensure the transpilation use-case is handled properly.
> [!NOTE]
> The [Cirq v1.5 …
=> QASM Parser and Related Transpilation Updated for Compatibility with Cirq v1.5
